### PR TITLE
feat: add search input component and page for it

### PR DESCRIPTION
**Pull request by DawidHaratyk**
# Overview:

closes #19 

Added search input page and SearchInput component with variants with label and without label as well

# Preview
image

### CODE REVIEW

**Comment by PoslinskiNet** [comment]
My first guess - it is a variation of the input - so I would go for merging those two into one (input). Another remark - this implementation already impacted generic input as well - please check it.

**Comment by k1eu** [comment]
as @PoslinskiNet said we can merge it into one item on the sidebar `Input` since basically it's what search is - Text input.
Please look into possibilities of integrating existing input code for it, also just as the input it can be full width for now

**Comment by PoslinskiNet** [comment]
@DawidHaratyk is it ready for review?

**Comment by DawidHaratyk** [comment]
> @DawidHaratyk is it ready for review?

Yes, it is, I've merged the search input component into "input" page

**Review by k1eu — APPROVED** [review]
Thanks! While u in the context can you try to fix the focus outlines on other inputs? I'll create a task for you
Visual representation of issue
image

**Comment by DawidHaratyk** [comment]
> Thanks! While u in the context can you try to fix the focus outlines on other inputs? I'll create a task for you Visual representation of issue image

Yes ofc :), can you create a task to fix that as you said?

**Pull request merged**
