### PR TITLE
feat: add selleo logos page

### LINKED ISSUE #62: [DEV] Add design system logo to CoreView
Details in parent story:
https://github.com/Selleo/design-system/issues/59

### PR DESCRIPTION
**Pull request by DawidHaratyk**
closes #62 

Added logos/signets page
Page contains basic and alternative versions of logos and signets
Added components for logos and signets

### CODE REVIEW

**Comment by PoslinskiNet** [comment]
@DawidHaratyk rename section to just "Logos".

I love the way how Volvo approaches their [design system](https://design.volvocars.com/). cc: @k1eu

**Review by k1eu — CHANGES_REQUESTED** [review]
Please include the necessary changes for logos in this PR. As @PoslinskiNet said we'd love to have it called just Logos under Brand section

**Comment by PoslinskiNet** [comment]
@DawidHaratyk also, resolve conflicts, please.

**Comment by DawidHaratyk** [comment]
> @DawidHaratyk also, resolve conflicts, please.

Right, already done! ;)

**Comment by PoslinskiNet** [comment]
@DawidHaratyk please change to `logo` - other components have a singular form always (if not, then also change please).

**Pull request merged**
