### PR TITLE
Feat/typography page

### LINKED ISSUE #61: [DEV] Add design system typography to CoreView
Details in parent story:
https://github.com/Selleo/design-system/issues/59

### PR DESCRIPTION
**Pull request by DawidHaratyk**
closes #61

Added typography page,
Merged colors and logos pages into that branch "feat/typography-page",
Remove preview from components in core section,

### CODE REVIEW

**Comment by k1eu** [comment]
- Please don't add commits with package-lock if not necessary - in that case you haven't installed anything so it's not necessary
- Each PR should only it's changes - so colors - colors, typo - typo, logo - logo
- That's why I told you to create a section first and the based everythin upon it
- Now the File Changes is bloated with other PRs changes and its hard to read

**Comment by k1eu** [comment]
Please fix the build issues so at least the preview is visible, you can replicate the error with buidling the app locally

**Comment by PoslinskiNet** [comment]
In reference to what @k1eu said, @DawidHaratyk for instance, you can start from HEAD of `master` -> `create a new branch`, `cherry-pick` what you want only and push with merge into this PR so it will update this PR 💡.

**Comment by PoslinskiNet** [comment]
@k1eu review please.

**Review by k1eu — APPROVED** [review]

**Pull request merged**
